# Generated by Django 5.1.3 on 2024-12-27 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'appointment_date'], name='medicalapp__user_id_6eefc6_idx'),
        ),
    ]
