# Generated by Django 5.1.3 on 2024-12-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0002_appointment_medicalapp__user_id_6eefc6_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
