# Generated by Django 5.1.3 on 2024-12-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0003_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medicalapp.doctor'),
        ),
    ]
