# Generated by Django 5.1.3 on 2024-12-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0005_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='medicalapp__user_id_6eefc6_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalapp.doctor'),
        ),
    ]
