# Generated by Django 5.1.3 on 2024-12-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0007_appointment_reason_doctor_availability_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='keyword',
            new_name='rule_type',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='response_text',
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_name',
            field=models.CharField(default='Default Rule Name', max_length=100),
        ),
    ]
