# Generated by Django 5.1.3 on 2024-12-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0008_rename_keyword_rule_rule_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
