# Generated by Django 5.1.3 on 2024-12-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0013_appointment_appointment_time_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_fee',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chat_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
