# Generated by Django 5.1.4 on 2024-12-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0016_doctor_consultation_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='appointmentDate',
        ),
    ]
