# Generated by Django 5.1.4 on 2024-12-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0018_rename_appointmentdate_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
